/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Spark API
 * Spark API
 * OpenAPI spec version: 0.1.0
 */

export type AuthTokensResponseTokenType = typeof AuthTokensResponseTokenType[keyof typeof AuthTokensResponseTokenType];


export const AuthTokensResponseTokenType = {
  Bearer: 'Bearer',
} as const;
