/**
 * Generated by orval v8.15.0 🍺
 * Do not edit manually.
 * Spark API
 * Spark API
 * OpenAPI spec version: 0.1.0
 */
import type { AuthTokensResponseTokenType } from './authTokensResponseTokenType';

export interface AuthTokensResponse {
  access_token?: string;
  refresh_token?: string;
  token_type?: AuthTokensResponseTokenType;
  /** アクセストークンの有効期限（秒） */
  expires_in?: number;
}
